### ISSUE TITLE
Hello，I want to ask you for some questions

### ISSUE THREAD

**Issue by Campary** [lukasValentin/OBIA4RTM#4]
I’m quite grateful for your shared code, it’s very well written, but I have some problems with this code, and I would like to ask you about these issues. When I input “from OBIA4RTM import install” and “install.install()”, I encounter these problems and can't solve them：

Settting up OBIA4RTM PostgreSQL backend
Connection to default Postgres Database failed!
Reason: connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
        Is the server running on that host and accepting TCP/IP connections?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\code\OBIA4RTM\OBIA4RTM\install.py", line 39, in install
    setup.setup_backend()
  File "D:\code\OBIA4RTM\OBIA4RTM\setup_db\setup_postgres.py", line 245, in setup_backend
    status = self.create_OBIA4RTM_DB()
  File "D:\code\OBIA4RTM\OBIA4RTM\setup_db\setup_postgres.py", line 86, in create_OBIA4RTM_DB
    con, cursor = self.connect_to_postgres()
  File "D:\code\OBIA4RTM\OBIA4RTM\setup_db\setup_postgres.py", line 72, in connect_to_postgres
    return con, cursor
UnboundLocalError: local variable 'con' referenced before assignment

I’m looking forward to your favorable reply at you earliest convenience.

**Comment by lukasValentin** [comment]
Hi @Campary sorry for not replying for such a long time - I'm not sure what is going on. You will have to provide much more details about your system and the way you setup PostgreSQL and PostGIS.

If you still are interested in using open-source software for Earth Observation Data Analysis I recommend you to switch from this repository to the [Earth Observation Data Analysis Library EOdal](https://github.com/EOA-team/eodal) available under GPL v3 license. With EOdal you can basically do most of the things from OBIA4RTM - with many more features and a much more generic programming interface (OBIA4RTM was my first serious Python package, since then I learned a lot of new cool stuff).

So, sorry again for the delay in my response. Let me know if you consider using EOdal and I'm happy to answer you any questions
